#pragma once
#include "ShipModule.h"
#include <vector>

namespace space {

// ─── ECS-idiomatic installed module components
// ──────────────────────────────── One component per module type attached to
// the ship entity. This allows registry.view<InstalledEngines>() without
// parsing a monolith.

struct InstalledEngines {
  std::vector<ModuleDef> modules;
  float totalThrust = 0.f;
  float totalRotSpeed = 0.f;
  // Both are regenerated by ShipOutfitter::applyBlueprint()
};

// InstalledWeapons holds catalogue IDs + derived stats.
// WeaponComponent retains runtime cooldown state for the combat system.
struct InstalledWeapons {
  std::vector<ModuleDef> modules;
  float damage = 0.f;
  float cooldown = 0.5f;
  float energyCost = 5.f;
};

struct InstalledShields {
  std::vector<ModuleDef> modules;
  float maxShield = 0.f;
  float regenRate = 0.f;
  float current = 0.f; // mutable shield level
};

struct InstalledCargo {
  std::vector<ModuleDef> modules;
  float capacity = 0.f;
  float used = 0.f;
};

struct InstalledPassengers {
  std::vector<ModuleDef> modules;
  float capacity = 0.f;
  float count = 0.f;
};

struct InstalledHabitation {
  std::vector<ModuleDef> modules;
  float totalCapacity = 0.f;
};

struct InstalledFuel {
  std::vector<ModuleDef> modules;
  float capacity = 0.f;
  float level = 0.f;
};

enum class CommandType { Cockpit, Bridge, Unmanned };

struct InstalledCommand {
  std::vector<ModuleDef> modules;
  CommandType type = CommandType::Cockpit;
  bool isStaffed = true;
  int staffingLevel = 1;
};

struct InstalledPower {
  std::vector<ModuleDef> modules;
  float output = 0.f;
  float isotopeFuel = 100.f; // Current fuel mass
};

struct InstalledBatteries {
  std::vector<ModuleDef> modules;
  float capacity = 0.f;
  float current = 0.f;
};

struct InstalledAmmo {
  std::vector<ModuleDef> racks;     // The ammo storage modules
  std::vector<AmmoStack> inventory; // Actual ammunition stored

  float usedVolume() const {
    float total = 0.0f;
    for (const auto &stack : inventory) {
      total += stack.type.volumePerRound * stack.count;
    }
    return total;
  }

  float totalCapacity() const {
    float total = 0.0f;
    for (const auto &rack : racks) {
      if (rack.hasAttribute(AttributeType::Capacity)) {
          Tier capTier = rack.getAttributeTier(AttributeType::Capacity);
          float mult = (capTier == Tier::T1) ? 1.0f : (capTier == Tier::T2 ? 3.0f : 8.0f);
          total += 100.0f * mult; // Standard capacity per rack tier
      } else {
          total += rack.volumeOccupied; // Fallback to volume if no attribute
      }
    }
    return total;
  }
};

struct InstalledReactionWheels {
  std::vector<ModuleDef> modules;
  float totalTurnRate = 0.f;
};

} // namespace space
