#pragma once
#include "game/components/ShipModule.h"
#include <vector>

namespace space {

// ─── ECS-idiomatic installed module components
// ──────────────────────────────── One component per module type attached to
// the ship entity. This allows registry.view<InstalledEngines>() without
// parsing a monolith.

struct InstalledEngines {
  std::vector<ModuleId> ids;
  float totalThrust = 0.f;
  float totalRotSpeed = 0.f;
  // Both are regenerated by ShipOutfitter::applyOutfit()
};

// InstalledWeapons holds catalogue IDs + derived stats.
// WeaponComponent retains runtime cooldown state for the combat system.
struct InstalledWeapons {
  std::vector<ModuleId> ids;
  float damage = 0.f;
  float cooldown = 0.5f;
  float energyCost = 5.f;
};

struct InstalledShields {
  std::vector<ModuleId> ids;
  float maxShield = 0.f;
  float regenRate = 0.f;
  float current = 0.f; // mutable shield level
};

struct InstalledCargo {
  std::vector<ModuleId> ids;
  float capacity = 0.f;
  float used = 0.f;
};

struct InstalledPassengers {
  std::vector<ModuleId> ids;
  float capacity = 0.f;
  float count = 0.f;
};

struct InstalledFuel {
  std::vector<ModuleId> ids;
  float capacity = 0.f;
  float level = 0.f;
};

struct InstalledPower {
  std::vector<ModuleId> ids;
  float output = 0.f;
};

} // namespace space
